success = true
perceived_trickiness = 4                                                                                 # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-27T10:47:29.083622+08:00
attempt_end_time = 2024-08-27T11:05:29.083622+08:00
reflections = """Tricky to implement quicly and accurately -- did it this time but need more practice""" # This is multiline!
