success = false
perceived_trickiness = 1 # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-13T22:18:45.9337+08:00
attempt_end_time = 2024-09-13T22:18:45.9337+08:00
reflections = """""" # This is multiline!
