success = true
perceived_trickiness = 2 # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-10T14:30:30.123143+08:00
attempt_end_time = 2024-08-10T14:36:30.123143+08:00
reflections = """collect cur sum and max sum distinctly.
core intuition: every time you visit a new number, you either start a new subarray or extend the previous.""" # This is multiline!
