success = false
perceived_trickiness = 6                                             # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-12T15:29:45.155986+08:00
attempt_end_time = 2024-08-12T15:59:45.155986+08:00
reflections = """Dynamic programmming problem... brain explode...""" # This is multiline!
