success = true
perceived_trickiness = 3                                                                      # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-09T14:29:34.458985+08:00
attempt_end_time = 2024-08-09T14:53:34.458985+08:00
reflections = """successfully wrote the BFS but a bit janky in figuring out the edge cases""" # This is multiline!
