success = true
perceived_trickiness = 4                                                                                                                      # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-10T16:06:17.4616+08:00
attempt_end_time = 2024-08-10T16:33:17.4616+08:00
reflections = """Still not entirely internalized. You move both if sum is zero, else you move left if sum too small, right is sum too big.""" # This is multiline!
