success = true
perceived_trickiness = 2                                            # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-19T13:27:46.03674+08:00
attempt_end_time = 2024-08-19T13:37:46.03674+08:00
reflections = """Need to learn the binary search template better""" # This is multiline!
