success = true
perceived_trickiness = 3                                                               # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-06T17:34:37.17754+08:00
attempt_end_time = 2024-09-06T17:53:37.17754+08:00
reflections = """using fixed size heap as leaderboard. Should learn quickselect too""" # This is multiline!
