success = true
perceived_trickiness = 2                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-02T13:38:03.920773+08:00
attempt_end_time = 2024-09-02T13:40:03.920773+08:00
reflections = """hash set for membership"""           # This is multiline!
