success = true
perceived_trickiness = 3                                                        # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-02T12:31:30.354254+08:00
attempt_end_time = 2024-09-02T12:58:30.354254+08:00
reflections = """Bsaically, writing an offset-based recursive descent parser""" # This is multiline!
