success = true
perceived_trickiness = 4                                                                      # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-28T16:14:36.799401+08:00
attempt_end_time = 2024-08-28T16:21:36.799401+08:00
reflections = """Greedy algo practice -- can compute subsections of journey independently.""" # This is multiline!
