success = true
perceived_trickiness = 2                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-07T09:08:23.774062+08:00
attempt_end_time = 2024-08-07T09:13:23.774062+08:00
reflections = """sum to n = n * n+1 / 2"""            # This is multiline!
