success = true
perceived_trickiness = 2                                    # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-18T20:24:32.942877+08:00
attempt_end_time = 2024-09-18T20:33:32.942877+08:00
reflections = """recursion tracking 2 values of interest""" # This is multiline!
