success = true
perceived_trickiness = 2                             # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-18T21:30:42.15502+08:00
attempt_end_time = 2024-09-18T21:36:42.15502+08:00
reflections = """vote counting algo"""               # This is multiline!
