success = true
perceived_trickiness = 2                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-07T09:01:23.932092+08:00
attempt_end_time = 2024-08-07T09:07:23.932092+08:00
reflections = """2-tier DFS"""                        # This is multiline!
