success = false
perceived_trickiness = 5                                                           # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-06T18:31:17.553348+08:00
attempt_end_time = 2024-09-06T18:50:17.553348+08:00
reflections = """can't figure out the formula for calculating rotated coords...""" # This is multiline!
