success = false
perceived_trickiness = 7                                   # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-08T10:18:31.411046+08:00
attempt_end_time = 2024-09-08T10:43:31.411046+08:00
reflections = """Didn't manage to internalize the trick""" # This is multiline!
