success = true
perceived_trickiness = 2                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-18T14:06:32.173255+08:00
attempt_end_time = 2024-09-18T14:14:32.173255+08:00
reflections = """linear-scan"""                       # This is multiline!
