success = true
perceived_trickiness = 3                                                         # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-09T14:55:29.652683+08:00
attempt_end_time = 2024-09-09T15:05:29.652683+08:00
reflections = """BST with extra step to convert between 1D index and 2D coord""" # This is multiline!
