success = true
perceived_trickiness = 3                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-14T13:48:40.179942+08:00
attempt_end_time = 2024-09-14T14:00:40.179942+08:00
reflections = """Practice prefix sums"""              # This is multiline!
