success = true
perceived_trickiness = 3 # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-02T10:01:05.387455+08:00
attempt_end_time = 2024-09-02T10:37:05.387455+08:00
reflections = """Conceptually simple but need to figure out clean backtracking template.
The crux: let the parent handle the child's path.
push left, search left, pop left.
alternatively, each node handles its own push and pop.
""" # This is multiline!
