success = true
perceived_trickiness = 3                                                                                                # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-07T10:04:25.897848+08:00
attempt_end_time = 2024-09-07T10:21:25.897848+08:00
reflections = """Tricky to implement correctly, but if you have your core heap understanding clear, you will be fine""" # This is multiline!
