success = true
perceived_trickiness = 5 # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-12T13:49:33.02754+08:00
attempt_end_time = 2024-09-12T15:08:33.02754+08:00
reflections = """I tried my best to write the parser following the crafting interpreters ideas... but now i see why you want to parse into tokens first.
Also, would probably be good to create the stack representation of the operations first
""" # This is multiline!
