success = true
perceived_trickiness = 1                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-19T11:53:18.646296+08:00
attempt_end_time = 2024-08-19T12:02:18.646296+08:00
reflections = """Straightforward, but done well."""   # This is multiline!
