success = true
perceived_trickiness = 2                                                                                                                             # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-07-29T13:24:17.208175+08:00
attempt_end_time = 2024-07-29T13:35:17.208175+08:00
reflections = """I got the correct answer but actually could have handled the different cases much more elegantly by checking for not-equal first""" # This is multiline!
