success = true
perceived_trickiness = 5                                      # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-21T18:11:09.021258+08:00
attempt_end_time = 2024-08-21T18:31:09.021258+08:00
reflections = """Coin change... still got me tripped up...""" # This is multiline!
