success = true
perceived_trickiness = 3                                       # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-15T13:33:35.569341+08:00
attempt_end_time = 2024-09-15T13:21:35.569341+08:00
reflections = """programming in go is really just different""" # This is multiline!
