success = false
perceived_trickiness = 1                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-29T09:57:29.720123+08:00
attempt_end_time = 2024-08-29T09:57:29.720123+08:00
reflections = """Need to learn the trick for this"""  # This is multiline!
