success = true
perceived_trickiness = 1                             # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-05T12:51:02.87248+08:00
attempt_end_time = 2024-08-05T12:57:02.87248+08:00
reflections = """Simple list iteration thingo"""     # This is multiline!
