success = true
perceived_trickiness = 3                                                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-30T08:40:29.823933+08:00
attempt_end_time = 2024-08-30T09:13:29.823933+08:00
reflections = """Got the right idea but bugs in initial impl. need to step through""" # This is multiline!
