success = true
perceived_trickiness = 2                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-15T15:39:59.305562+08:00
attempt_end_time = 2024-09-15T15:48:59.305562+08:00
reflections = """backtracking practice"""             # This is multiline!
