success = false
perceived_trickiness = 6                                             # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-01T12:16:46.714349+08:00
attempt_end_time = 2024-08-01T12:16:46.714349+08:00
reflections = """Deferring all binary-operation questions for now""" # This is multiline!
