success = true
perceived_trickiness = 4 # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-22T15:49:48.963859+08:00
attempt_end_time = 2024-08-22T16:15:48.963859+08:00
reflections = """Close, but path management is off.
If doing recursive backtracking, it can be helpful to parameterize the path so that you can discard the path implicitly with the stack
""" # This is multiline!
