success = true
perceived_trickiness = 3                             # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-10T12:19:04.01023+08:00
attempt_end_time = 2024-09-10T12:23:04.01023+08:00
reflections = """in order practice"""                # This is multiline!
