success = true
perceived_trickiness = 3                                  # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-17T14:00:36.278738+08:00
attempt_end_time = 2024-09-17T14:03:36.278738+08:00
reflections = """using fixed sized heap as leaderboard""" # This is multiline!
