success = true
perceived_trickiness = 2                               # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-08T11:42:04.1652+08:00
attempt_end_time = 2024-09-08T11:53:04.1652+08:00
reflections = """Relatively simple multi source bfs""" # This is multiline!
