success = true
perceived_trickiness = 1                                            # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-08T12:02:11.06887+08:00
attempt_end_time = 2024-08-08T12:20:11.06887+08:00
reflections = """Practice top-down DP approach using memoization""" # This is multiline!
