success = true
perceived_trickiness = 2                                  # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-10T14:05:04.063221+08:00
attempt_end_time = 2024-08-10T14:13:04.063221+08:00
reflections = """2 separate sets of recursion criteria""" # This is multiline!
