success = true
perceived_trickiness = 2                                     # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-21T09:20:18.433943+08:00
attempt_end_time = 2024-08-21T09:26:18.433943+08:00
reflections = """practice 2 different levels of recursion""" # This is multiline!
