success = false
perceived_trickiness = 6                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-13T16:08:19.924561+08:00
attempt_end_time = 2024-08-13T16:19:19.924561+08:00
reflections = """Time to learn union find"""          # This is multiline!
