success = true
perceived_trickiness = 4                                            # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-21T15:22:49.460106+08:00
attempt_end_time = 2024-08-21T15:45:49.460106+08:00
reflections = """Tricky to implement cleanly, but good practice!""" # This is multiline!
