success = true
perceived_trickiness = 1                                                                                                                         # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-20T15:58:18.302864+08:00
attempt_end_time = 2024-08-20T15:31:18.302864+08:00
reflections = """Need to focus up and write cleaner simple code. This was just easy sliding windows, but got tripped up by basic flow control""" # This is multiline!
