success = true
perceived_trickiness = 2                                           # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-21T14:52:57.06441+08:00
attempt_end_time = 2024-08-21T15:04:57.06441+08:00
reflections = """Remember to check your iteration conditions...""" # This is multiline!
