success = true
perceived_trickiness = 6                                                                                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-12T13:47:11.67891+08:00
attempt_end_time = 2024-08-12T13:02:11.67891+08:00
reflections = """discrete time tracking is tricky... best to attach time snapshots to the payloads being processed""" # This is multiline!
