success = true
perceived_trickiness = 2                                            # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-19T18:12:18.279606+08:00
attempt_end_time = 2024-08-19T18:18:18.279606+08:00
reflections = """Just need to remember the vote counting trick..""" # This is multiline!
