success = true
perceived_trickiness = 2                                # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-21T08:33:09.971873+08:00
attempt_end_time = 2024-08-21T08:36:09.971873+08:00
reflections = """Using a pointer to bubble up zeroes""" # This is multiline!
