success = true
perceived_trickiness = 3                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-15T16:22:20.850129+08:00
attempt_end_time = 2024-09-15T16:36:20.850129+08:00
reflections = """prefix sum practice"""               # This is multiline!
