success = true
perceived_trickiness = 2                                            # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-23T19:54:28.760733+08:00
attempt_end_time = 2024-08-23T20:10:28.760733+08:00
reflections = """Remember to use your memo... good job otherwise""" # This is multiline!
