success = true
perceived_trickiness = 2                             # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-10T13:38:00.12195+08:00
attempt_end_time = 2024-08-10T13:41:00.12195+08:00
reflections = """Reverse-half-number"""              # This is multiline!
