success = true
perceived_trickiness = 5                                                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-30T11:22:51.932937+08:00
attempt_end_time = 2024-08-30T11:27:51.932937+08:00
reflections = """You don't need do-while semantics.
You just need to be clear about how you're initializing your values.
""" # This is multiline!
