success = true
perceived_trickiness = 2                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-25T11:26:23.308772+08:00
attempt_end_time = 2024-08-25T11:40:23.308772+08:00
reflections = """Dynamic programming practice"""      # This is multiline!
