success = true
perceived_trickiness = 2                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-28T09:14:19.380565+08:00
attempt_end_time = 2024-08-28T09:34:19.380565+08:00
reflections = """Bottom up DP with memo"""            # This is multiline!
