success = true
perceived_trickiness = 2                                               # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-17T13:46:01.663261+08:00
attempt_end_time = 2024-08-17T14:08:01.663261+08:00
reflections = """It felt much longer than it actually was... 25 min""" # This is multiline!
