success = true
perceived_trickiness = 1                                                                       # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-24T20:02:41.165171+08:00
attempt_end_time = 2024-08-24T20:25:41.165171+08:00
reflections = """empty string, single-char, two-char string are notable edge cases to cover""" # This is multiline!
