success = true
perceived_trickiness = 3                                                 # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-07T16:19:21.733432+08:00
attempt_end_time = 2024-08-07T16:23:21.733432+08:00
reflections = """sliding window algo + jump to keep left internalized""" # This is multiline!
