success = true
perceived_trickiness = 2                                                                   # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-07-30T11:57:00.946423+08:00
attempt_end_time = 2024-07-30T11:12:00.946423+08:00
reflections = """Not too complex, just need to be clear about stack and queue semantics""" # This is multiline!
