success = true
perceived_trickiness = 5                                                                       # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-05T11:57:10.855987+08:00
attempt_end_time = 2024-09-05T12:18:10.855987+08:00
reflections = """Recursive merge sort... relies on first splitting the list no matter what.""" # This is multiline!
