success = true
perceived_trickiness = 2                                                                                           # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-10T15:12:02.298936+08:00
attempt_end_time = 2024-08-10T15:18:02.298936+08:00
reflections = """Learn the distinct approaches properly -- also note how you're defining your in between ranges""" # This is multiline!
