success = true
perceived_trickiness = 4                                   # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-11T10:27:53.291234+08:00
attempt_end_time = 2024-09-11T10:51:53.291234+08:00
reflections = """quite a bit of code but good first-try""" # This is multiline!
