success = true
perceived_trickiness = 1                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-19T17:11:26.613371+08:00
attempt_end_time = 2024-08-19T17:13:26.613371+08:00
reflections = """Hash lookup practice"""              # This is multiline!
