success = true
perceived_trickiness = 3                                 # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-08T17:48:05.145733+08:00
attempt_end_time = 2024-09-08T17:59:05.145733+08:00
reflections = """Topological-order traversal practice""" # This is multiline!
