success = true
perceived_trickiness = 2                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-01T08:54:56.292744+08:00
attempt_end_time = 2024-08-01T08:56:56.292744+08:00
reflections = """got the algo right this time"""      # This is multiline!
