success = true
perceived_trickiness = 3                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-08T18:01:34.402222+08:00
attempt_end_time = 2024-09-08T18:13:34.402222+08:00
reflections = """dfs practice"""                      # This is multiline!
