success = true
perceived_trickiness = 4                                                                                                # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-11T12:45:35.927738+08:00
attempt_end_time = 2024-09-11T13:27:35.927738+08:00
reflections = """Slow to solve because I ran down the wrong route of unidirectional / order-based traversal at first""" # This is multiline!
