success = true
perceived_trickiness = 5                                # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-23T11:06:11.920423+08:00
attempt_end_time = 2024-09-23T11:35:11.920423+08:00
reflections = """using stacks to keep track of scope""" # This is multiline!
