success = true
perceived_trickiness = 6                                                                                                                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-07-29T11:10:29.137402+08:00
attempt_end_time = 2024-07-29T11:15:29.137402+08:00
reflections = """Need to practice more, and remember that you only need max profit as the answer, without needing the buy and sell days themselves""" # This is multiline!
