success = true
perceived_trickiness = 3                                                                                    # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-20T10:34:15.76098+08:00
attempt_end_time = 2024-08-20T10:54:15.76098+08:00
reflections = """Need to allow all strings to be fully processed with the or condition in the while loop""" # This is multiline!
