success = true
perceived_trickiness = 2                                                     # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-10T15:38:58.153476+08:00
attempt_end_time = 2024-08-10T15:48:58.153476+08:00
reflections = """Practice max heap solution. Need to look at quickselect!""" # This is multiline!
