success = true
perceived_trickiness = 3                                    # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-07T09:30:11.584979+08:00
attempt_end_time = 2024-09-07T09:43:11.584979+08:00
reflections = """It's easier when you track the corners.""" # This is multiline!
