success = true
perceived_trickiness = 2                                                                                                                                       # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-07T11:12:07.176852+08:00
attempt_end_time = 2024-08-07T11:22:07.176852+08:00
reflections = """almost failed... need to remember that you need to iterate through mat twice, once starting from top left, once starting from bottom right""" # This is multiline!
