success = true
perceived_trickiness = 4                                                                       # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-07-31T11:46:31.938586+08:00
attempt_end_time = 2024-07-31T11:52:31.938586+08:00
reflections = """Better... work up from least significant bits, get comfy with while loops!""" # This is multiline!
