success = true
perceived_trickiness = 2                                                                   # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-21T15:13:25.316517+08:00
attempt_end_time = 2024-08-21T15:21:25.316517+08:00
reflections = """Two pointer approach, keeping start back to exclude repeated character""" # This is multiline!
