success = true
perceived_trickiness = 7                                                                                                                                   # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-12T10:49:14.946388+08:00
attempt_end_time = 2024-08-12T10:58:14.946388+08:00
reflections = """Need to study memoization + relationship with tabulation and try again... but for now it seems like tabulation is more intuitive to me""" # This is multiline!
