success = true
perceived_trickiness = 1                                                                           # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-21T09:27:59.594913+08:00
attempt_end_time = 2024-08-21T09:34:59.594913+08:00
reflections = """work into middle from edges, then reverse since list is built in reverse order""" # This is multiline!
