success = true
perceived_trickiness = 2                                             # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-22T09:56:25.769994+08:00
attempt_end_time = 2024-08-22T10:02:25.769994+08:00
reflections = """Learnt the top-down dp with memoization approach""" # This is multiline!
