success = true
perceived_trickiness = 2                                                                                                                           # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-12T11:09:23.655662+08:00
attempt_end_time = 2024-08-12T11:17:23.655662+08:00
reflections = """min stack is jsut two stacks to track the snapshot of element ordering and snapshot of min element at each point respectively.""" # This is multiline!
