success = true
perceived_trickiness = 3                                                       # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-05T11:27:25.086578+08:00
attempt_end_time = 2024-08-05T11:49:25.086578+08:00
reflections = """Need to keep practicing... success but still a bit finicky""" # This is multiline!
