success = true
perceived_trickiness = 3 # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-10T13:42:46.028816+08:00
attempt_end_time = 2024-08-10T13:56:46.028816+08:00
reflections = """With binary search algos, you generally need to have a strong and consistent picture of whether your ranges are inclusive or exclusive of the end. 
Generally, easiest if you do the standard thing and include the start but exclude the end.""" # This is multiline!
