success = false
perceived_trickiness = 3 # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-07-31T08:45:02.092204+08:00
attempt_end_time = 2024-07-31T09:02:02.092204+08:00
reflections = """You need to brush up on your linked list handling
Be mindful of setting up reference cycles.
If you're assigning a reference to some var, you should check to make sure you haven't already reassigned *that* reference.
When revising, try the recursive method (propagate reference to new head + a given scope gives you reference to new tail).
""" # This is multiline!
