success = true
perceived_trickiness = 3                                                             # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-19T11:37:36.090414+08:00
attempt_end_time = 2024-08-19T11:49:36.090414+08:00
reflections = """Always a bit bendy, this, but i remember how to reason about it!""" # This is multiline!
