success = true
perceived_trickiness = 3 # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-07-29T12:02:36.24664+08:00
attempt_end_time = 2024-07-29T12:02:36.24664+08:00
reflections = """Good chance to practice applying the binary search template:
https://leetcode.com/discuss/general-discussion/786126/python-powerful-ultimate-binary-search-template-solved-many-problems
""" # This is multiline!
