success = true
perceived_trickiness = 1                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-19T12:03:54.981019+08:00
attempt_end_time = 2024-09-19T12:08:54.981019+08:00
reflections = """hash based solution"""               # This is multiline!
