success = true
perceived_trickiness = 2                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-22T10:03:46.890385+08:00
attempt_end_time = 2024-08-22T10:10:46.890385+08:00
reflections = """two passes to accumulate product"""  # This is multiline!
