success = true
perceived_trickiness = 3                                  # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-23T19:36:27.46824+08:00
attempt_end_time = 2024-08-23T19:53:27.46824+08:00
reflections = """good job walking through a test case.""" # This is multiline!
