success = true
perceived_trickiness = 2                                                                          # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-07T10:40:08.676962+08:00
attempt_end_time = 2024-08-07T10:44:08.676962+08:00
reflections = """two-tier recursion to separate out needing exact match vs. needing root match""" # This is multiline!
