success = true
perceived_trickiness = 2                                                                                                                      # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-22T12:19:53.354566+08:00
attempt_end_time = 2024-08-22T12:36:53.354566+08:00
reflections = """top-down dp correctly solves the solution but you should get comfortable with backtracking as an addition to your arsenal""" # This is multiline!
