success = true
perceived_trickiness = 2                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-04T17:17:02.144596+08:00
attempt_end_time = 2024-09-04T17:36:02.144596+08:00
reflections = """Linked list + calc operations"""     # This is multiline!
