success = false
perceived_trickiness = 6 # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-05T09:04:23.802295+08:00
attempt_end_time = 2024-09-05T10:00:23.802295+08:00
reflections = """On some level this is a simple backtracking problem but it seems there is some depth to the way you handle the not-nest case.
Suspect using array of linked lists is the way to approach this.
Core idea: if you want valid parentheses
- You can only add open parens if closed count == open count
- You have a valid combo when your closed and open are the same
""" # This is multiline!
