success = true
perceived_trickiness = 3                                                             # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-09T10:50:19.27712+08:00
attempt_end_time = 2024-09-09T11:10:19.27712+08:00
reflections = """Doesn't look good; this is O(n^2) solution, time to learn better""" # This is multiline!
