success = true
perceived_trickiness = 1                                     # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-20T10:09:03.009241+08:00
attempt_end_time = 2024-08-20T10:18:03.009241+08:00
reflections = """Straight forward hash set based approach""" # This is multiline!
