success = true
perceived_trickiness = 1                                                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-19T13:16:12.244329+08:00
attempt_end_time = 2024-08-19T13:21:12.244329+08:00
reflections = """pay attention to edge cases where in s but not in t or vice versa""" # This is multiline!
