success = true
perceived_trickiness = 3                                                            # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-10T11:22:08.460785+08:00
attempt_end_time = 2024-09-10T11:45:08.460785+08:00
reflections = """Wasn't particularly challenging, just needed to be more careful""" # This is multiline!
