success = true
perceived_trickiness = 3                                                                    # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-06T18:04:20.427923+08:00
attempt_end_time = 2024-08-06T18:10:20.427923+08:00
reflections = """Practiced the max-heap trick to keep heap size constant as leaderboard.""" # This is multiline!
