success = true
perceived_trickiness = 3                                                     # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-09T09:30:15.326004+08:00
attempt_end_time = 2024-08-09T09:38:15.326004+08:00
reflections = """practiced using mins stack. stacks for leader snapshots!""" # This is multiline!
