success = true
perceived_trickiness = 2                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-12T11:35:06.374463+08:00
attempt_end_time = 2024-08-12T11:46:06.374463+08:00
reflections = """DFS with in place mod"""             # This is multiline!
