success = true
perceived_trickiness = 1                                        # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-07-29T08:57:07.177458+08:00
attempt_end_time = 2024-07-29T09:15:07.177458+08:00
reflections = """Simple application of a stack + lookup dict""" # This is multiline!
