success = true
perceived_trickiness = 2                                                                                                                           # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-07T17:38:13.858264+08:00
attempt_end_time = 2024-08-07T17:54:13.858264+08:00
reflections = """used nested deques, but can save on that by keeping track in the outer loop how many to pop before considering this level done""" # This is multiline!
