success = true
perceived_trickiness = 2                                                                                                               # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-01T09:14:18.109939+08:00
attempt_end_time = 2024-08-01T09:16:18.109939+08:00
reflections = """Mainly need to keep track of conditions to get that final iteration count correct... it comes down to the boundary""" # This is multiline!
