success = true
perceived_trickiness = 3                                                         # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-18T15:44:21.398564+08:00
attempt_end_time = 2024-08-18T16:00:21.398564+08:00
reflections = """Simple, but need to be thoughtful about catchihng edge cases""" # This is multiline!
