success = true
perceived_trickiness = 5                                                                                     # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-07T12:29:06.169369+08:00
attempt_end_time = 2024-08-07T12:34:06.169369+08:00
reflections = """Subtle application of sliding windows... need to think about how to keep the left marker""" # This is multiline!
