success = true
perceived_trickiness = 2                                             # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-02T09:42:12.539888+08:00
attempt_end_time = 2024-09-02T09:55:12.539888+08:00
reflections = """reverse output list every other level. that's it""" # This is multiline!
