success = true
perceived_trickiness = 3                                                                                                       # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-17T13:32:20.006672+08:00
attempt_end_time = 2024-09-17T13:39:20.006672+08:00
reflections = """Be clear about what you are making discrete, and what you are making continuous, when dealing with randoms""" # This is multiline!
