success = true
perceived_trickiness = 1                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-20T10:56:09.491793+08:00
attempt_end_time = 2024-08-20T10:59:09.491793+08:00
reflections = """recursive tree checking"""           # This is multiline!
