success = true
perceived_trickiness = 2                                                # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-29T12:27:15.061615+08:00
attempt_end_time = 2024-08-29T12:31:15.061615+08:00
reflections = """Need to track min so far as well for sign inversion""" # This is multiline!
