success = true
perceived_trickiness = 4                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-09T10:21:15.720645+08:00
attempt_end_time = 2024-08-09T10:47:15.720645+08:00
reflections = """"""                                  # This is multiline!
