success = true
perceived_trickiness = 4                                                                                                                           # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-06T17:03:46.257477+08:00
attempt_end_time = 2024-08-06T17:15:46.257477+08:00
reflections = """I should definitely revise this... simple to code up once you understand it but i don't think i fully understand the trick yet""" # This is multiline!
