success = true
perceived_trickiness = 2                                                                                                # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-21T08:58:07.508001+08:00
attempt_end_time = 2024-08-21T09:05:07.508001+08:00
reflections = """in arrays-as-binary-tree situations, indexes CAN overlap. because if they do your mid just == left.""" # This is multiline!
