success = true
perceived_trickiness = 3                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-08T18:20:17.519485+08:00
attempt_end_time = 2024-09-08T18:24:17.519485+08:00
reflections = """List reversals"""                    # This is multiline!
