success = true
perceived_trickiness = 3                                                  # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-10T10:33:35.103048+08:00
attempt_end_time = 2024-09-10T11:01:35.103048+08:00
reflections = """Not a very clean solution, but a solution nonetheless""" # This is multiline!
