success = false
perceived_trickiness = 3                                                                # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-29T11:41:48.850782+08:00
attempt_end_time = 2024-08-29T11:59:48.850782+08:00
reflections = """I got tricked because i didn't handle the case of negative numbers """ # This is multiline!
