success = true
perceived_trickiness = 3                                                                                                                                                                       # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-23T16:27:31.445517+08:00
attempt_end_time = 2024-08-23T17:00:31.445517+08:00
reflections = """Not too bad in terms of walking through a test case, good accuracy. Just need to keep working hard on the practice and get faster on stepping through a good, minimal test""" # This is multiline!
