success = true
perceived_trickiness = 2                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-18T21:37:49.990094+08:00
attempt_end_time = 2024-09-18T21:52:49.990094+08:00
reflections = """code gets long"""                    # This is multiline!
