success = true
perceived_trickiness = 2                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-10T14:00:01.970829+08:00
attempt_end_time = 2024-08-10T14:02:01.970829+08:00
reflections = """leverge u32 property"""              # This is multiline!
