success = false
perceived_trickiness = 3                                                     # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-07-31T09:14:28.924415+08:00
attempt_end_time = 2024-07-31T09:26:28.924415+08:00
reflections = """Just need to learn the boyer moore vote counting algo...""" # This is multiline!
