success = true
perceived_trickiness = 2                                                                                                                                  # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-07-29T09:34:49.165428+08:00
attempt_end_time = 2024-07-29T10:00:49.165428+08:00
reflections = """As with linked list questions... just need to be pateint and think through possible cases, make sure edge cases are handled correctly""" # This is multiline!
