success = true
perceived_trickiness = 2                                                                                                                                          # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-07-30T10:53:34.533527+08:00
attempt_end_time = 2024-07-30T10:58:34.533527+08:00
reflections = """Good job remembering this time around that you don't need to return the start and end dates, only the max profit, and to use that information""" # This is multiline!
