success = true
perceived_trickiness = 2                                            # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-07T10:45:32.926459+08:00
attempt_end_time = 2024-08-07T10:51:32.926459+08:00
reflections = """using iteration from both ends this time around""" # This is multiline!
