success = true
perceived_trickiness = 4                                                                                                                 # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-05T14:21:36.773801+08:00
attempt_end_time = 2024-08-05T14:47:36.773801+08:00
reflections = """You need to keep your binary cheat sheet out with you... and in this case leverage the fact that you know it's a u32""" # This is multiline!
