success = true
perceived_trickiness = 3                             # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-22T16:23:54.72607+08:00
attempt_end_time = 2024-08-22T16:28:54.72607+08:00
reflections = """Backtracking practice"""            # This is multiline!
