success = false
perceived_trickiness = 7                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-19T09:37:06.318061+08:00
attempt_end_time = 2024-09-19T10:30:06.318061+08:00
reflections = """This is really hard"""               # This is multiline!
