success = true
perceived_trickiness = 2                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-30T09:53:51.980145+08:00
attempt_end_time = 2024-08-30T10:06:51.980145+08:00
reflections = """BFS gives shortest path"""           # This is multiline!
