success = true
perceived_trickiness = 3                               # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-09T09:38:54.234024+08:00
attempt_end_time = 2024-08-09T09:45:54.234024+08:00
reflections = """Practiced stack-of-tuples approach""" # This is multiline!
