success = true
perceived_trickiness = 3                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-07T08:58:14.472634+08:00
attempt_end_time = 2024-08-07T09:00:14.472634+08:00
reflections = """Internalized minesweeper algo"""     # This is multiline!
