success = false
perceived_trickiness = 7 # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-30T10:21:07.773795+08:00
attempt_end_time = 2024-08-30T10:52:07.773795+08:00
reflections = """Can find nlogn and n^2 solutions but not n.
Turns out the solution is to treat input as a linked list... devilish!
""" # This is multiline!
