success = true
perceived_trickiness = 3                                                                        # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-15T15:28:13.901435+08:00
attempt_end_time = 2024-09-15T15:35:13.901435+08:00
reflections = """Linked list practice (found some new ways to handle edge cases more neatly)""" # This is multiline!
