success = true
perceived_trickiness = 2                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-22T10:11:18.012844+08:00
attempt_end_time = 2024-08-22T10:14:18.012844+08:00
reflections = """straightforward"""                   # This is multiline!
