success = true
perceived_trickiness = 1                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-19T13:54:36.357113+08:00
attempt_end_time = 2024-08-19T14:02:36.357113+08:00
reflections = """BFS for floodfill"""                 # This is multiline!
