success = true
perceived_trickiness = 2                                                                                                                      # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-25T12:26:43.334065+08:00
attempt_end_time = 2024-08-25T12:38:43.334065+08:00
reflections = """using backtracking for combinatorials. Easier because using the call stack to impliciiytyly take care of the backtracking""" # This is multiline!
