success = true
perceived_trickiness = 2                                                                       # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-17T15:19:21.773063+08:00
attempt_end_time = 2024-08-17T15:23:21.773063+08:00
rweflections = """Just need to track the last node in each level in a level order traversal""" # This is multiline!
