success = true
perceived_trickiness = 2                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-19T12:08:45.184874+08:00
attempt_end_time = 2024-09-19T12:20:45.184874+08:00
reflections = """tricky string parsing stuff"""       # This is multiline!
