success = true
perceived_trickiness = 5                                                                                                 # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-08T17:32:10.53994+08:00
attempt_end_time = 2024-09-08T17:43:10.53994+08:00
reflections = """this dp programming approach is a bit weird becaue doesn't automatically explore all possible states""" # This is multiline!
