success = true
perceived_trickiness = 1                             # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-24T19:53:13.35535+08:00
attempt_end_time = 2024-08-24T20:01:13.35535+08:00
reflections = """Good practice"""                    # This is multiline!
