success = true
perceived_trickiness = 2                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-18T16:15:14.199806+08:00
attempt_end_time = 2024-08-18T16:29:14.199806+08:00
reflections = """Simple dp application"""             # This is multiline!
