success = true
perceived_trickiness = 2                                                                                                                  # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-06T15:13:23.246023+08:00
attempt_end_time = 2024-08-06T15:47:23.246023+08:00
reflections = """overlaps function needs to be correct at all edges... maybe keep some blocks and needles with you for coding practice""" # This is multiline!
