success = true
perceived_trickiness = 1                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-19T16:42:17.918875+08:00
attempt_end_time = 2024-08-19T16:47:17.918875+08:00
reflections = """basic application of binsrc"""       # This is multiline!
