success = true
perceived_trickiness = 1                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-09-18T15:10:35.266817+08:00
attempt_end_time = 2024-09-18T15:14:35.266817+08:00
reflections = """Binary search impl practice"""       # This is multiline!
