success = false
perceived_trickiness = 6                                                  # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-01T11:06:01.170126+08:00
attempt_end_time = 2024-08-01T11:13:01.170126+08:00
reflections = """Very unfamiliar at this point with bitwise operations""" # This is multiline!
