success = true
perceived_trickiness = 5                                                                                                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-15T09:09:21.741788+08:00
attempt_end_time = 2024-08-15T09:31:21.741788+08:00
reflections = """A bit more unintuitive, but relies on the use of hub emails (also same intuition underlying union find, I suppose""" # This is multiline!
