success = false
perceived_trickiness = 1 # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-31T16:48:58.124946+08:00
attempt_end_time = 2024-08-31T16:48:58.124946+08:00
reflections = """
This is pretty tricky...
Should definitely revise this
Need to come back to this, bigtime
""" # This is multiline!
