success = true
perceived_trickiness = 2                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-22T11:43:54.475705+08:00
attempt_end_time = 2024-08-22T11:54:54.475705+08:00
reflections = """Tricky bin srch"""                   # This is multiline!
