success = true
perceived_trickiness = 4                                                 # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-26T15:05:44.32243+08:00
attempt_end_time = 2024-08-26T15:35:44.32243+08:00
reflections = """Linked lists are tricky to do quickly and accurately""" # This is multiline!
