success = false
perceived_trickiness = 1 # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-07T09:21:02.437332+08:00
attempt_end_time = 2024-08-07T09:21:02.437332+08:00
reflections = """""" # This is multiline!
