success = true
perceived_trickiness = 3                                                                      # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-05T12:31:42.189053+08:00
attempt_end_time = 2024-08-05T12:45:42.189053+08:00
reflections = """You seem to be stronger with graphs / trees and not as strong with arrays""" # This is multiline!
