success = true
perceived_trickiness = 3                              # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-29T12:32:46.399175+08:00
attempt_end_time = 2024-08-29T12:57:46.399175+08:00
reflections = """trie + dfs to handle wildcarding"""  # This is multiline!
