success = false
perceived_trickiness = 1 # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-16T16:55:47.241407+08:00
attempt_end_time = 2024-08-16T16:55:47.241407+08:00
reflections = """""" # This is multiline!
