success = true
perceived_trickiness = 2                                                     # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-21T09:35:28.809847+08:00
attempt_end_time = 2024-08-21T09:43:28.809847+08:00
reflections = """Need to learn to discern when greedy solution is optimal""" # This is multiline!
