success = true
perceived_trickiness = 2                                                         # 7-point scale: 1 is brain-dead, 7 is diabolical
attempt_start_time = 2024-08-24T17:55:49.990634+08:00
attempt_end_time = 2024-08-24T18:21:49.990634+08:00
reflections = """to be safe, use truncating division in this kind of scenario""" # This is multiline!
